### ISSUE TITLE
Could you please ask what tools did you use to make the installation package for each platform?

### ISSUE THREAD

**Issue by westinyang** [rladstaetter/LogoRRR#44]
Could you please ask what tools did you use to make the installation package for each platform?

**Comment by rladstaetter** [comment]
I have written a [short summary what technologies are in use](https://github.com/rladstaetter/LogoRRR/blob/main/Technology.md), I hope this answers your questions. 

Thank you for your interest in LogoRRR! I hope it serves your use case. 🙂

**Comment by westinyang** [comment]
> I have written a [short summary what technologies are in use](https://github.com/rladstaetter/LogoRRR/blob/main/Technology.md), I hope this answers your questions.
> 
> Thank you for your interest in LogoRRR! I hope it serves your use case. 🙂

Thank you very much. This is absolutely wonderful. I have read a lot of materials and projects and learned a lot from your project.  We have a common goal of having JavaFX and GraalVM create applications together. I have spent the last few months learning and trying to use GraalVM Native Image to build command line applications (PICO), desktop applications (JavaFX), Web applications (SpringBoot),  I feel that this event is the motivation for me to give up learning Golang, haha.  Finally also put my project address: https://github.com/westinyang/java-graalvm-start, learn from each other!  (I used machine translation for this paragraph, I don't know whether it can be expressed accurately.)

**Comment by rladstaetter** [comment]
Great to see that it helped you with your open source work. If you want to stay informed about new releases you can follow the official [twitter account ](https://www.twitter.com/logorrr/) where new releases are announced. 

Alternatively you can fork this project and contribute via pull requests, this would be awesome. Maybe try out Scala as well, it is a nice language! Cheers.
